apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-frontend.fullname" . }}-env-config
  labels:
    {{- include "demo-frontend.labels" . | nindent 4 }}
data:
  env-config.js: |
    window._env_ = {
      BACKEND_URL: {{ .Values.backendUrl | quote }}
    };
